version: '3.2'
services:
  proxy:
    image: nginx:alpine
    ports:
      - '80:80'
    networks:
      - 'tap_obscore'
    volumes:
      - './proxy/default.conf:/etc/nginx/conf.d/default.conf'
    depends_on: 
      - 'tap_obscore'
  tap_obscore:
    image: opencadc/tap-obscore:alma-alpine
    build: ./
    ports:
      - '8080:8080'      
      - '5555:5555'
    networks:
      - 'tap_obscore'
    env_file:
      - './config/alma-tap.properties'

networks:
  tap_obscore:
