version: '3.2'
services:
  tap_obscore:
    image: opencadc/tap-obscore:alma-alpine
    build: ./
    ports:
      - '8080:8080'
      - '5555:5555'
    depends_on:
      - 'tapdb'
    networks:
      - 'tap_obscore'
    environment: 
      CATALINA_OPTS: "-Dtapuser.jdbc.username=TAP_SCHEMA -Dtapuser.jdbc.password=TAP_SCHEMA -Dtapuser.jdbc.driverClassName=oracle.jdbc.OracleDriver -Dtapuser.jdbc.url=jdbc:oracle:thin:@tapdb:1521/XE"
  tapdb:
    image: opencadc/tap-oracle:11-xe
    shm_size: 1gb
    networks:
      - 'tap_obscore'
    volumes:
      - './sql:/docker-entrypoint-initdb.d/startup'

networks:
  tap_obscore:
